export const QUERY_KEYS = {
    Manufacturers: "manufacturers",
    Models: "models",
    Bikes: "bikes",
    WheelSizes: "wheelSizes",
    Colors: "colors",
    Categories: "categories",
    Statuses: "statuses",
    Places: "places",
    Employees: "employees",
    Users: "users",
    Repairs: "repairs",
    Services: "services",
    Units: "units",
    Parts: "parts",
    PartCategories: "partCategories",
    ServiceCategories: "serviceCategories",
};
