export const QUERY_KEYS = {
  Manufacturers: "manufacturers",
  Models: "models",
  Bikes: "bikes",
  WheelSizes: "wheelSizes",
  Colors: "colors",
  Categories: "categories",
  Statuses: "statuses",
  Places: "places",
  Employees: "employees",
  Users: "users",
  Repairs: "repairs",
  Units: "units",
  Parts: "parts",
  PartCategories: "partCategories",
};
