import Invoice from '../app/dostawy/faktury/[id]/page';

const URLS = {
  Manufacturers: '/Manufacturers/',
  Models: '/Models/',
  Bikes: '/Bikes/bikesByModelId/',
  Bikes2: '/Bikes/',
  WheelSizes: '/WheelSizes/',
  Colors: '/Colors/',
  Categories: '/Categories/',
  Statuses: '/Statuses/',
  PlacesNotStorage: '/Places/NotStorage/',
  Places: '/Places/',
  Employees: '/Employees/',
  Users: '/Users/',
  Repairs: '/Repairs/',
  Services: '/Services/',
  Units: '/Units/',
  Parts: '/Parts/',
  PartCategories: '/PartTypes/Categories/',
  PartTypes: '/PartTypes/',
  ServiceCategories: '/Services/Categories/',
  Favorites: '/Favorites/',
  ExcludedStatuses: '/Statuses/Excluded/',
  SoldBikes: '/SalesData/Sold/',
  ServicesFromCategory: '/Services/FromCategory/',
  FilteredParts: '/Parts/Filtered/',
  NotAssignedInvoice: '/Invoice/NotAssignedInvoice/',
  NewDelivery: '/Deliveries/create/',
  NewInvoice: '/Invoice/',
  Invoice: '/Invoice/',
  Invoices: '/Invoice/',
  Deliveries: '/Deliveries/',
  Delivery: '/Deliveries/',
  StartDelivery: '/Deliveries/start/',
  FinishDelivery: '/Deliveries/finish/',
  CancelDelivery: '/Deliveries/cancel/',
  DeliveryDocuments: '/DeliveryDocuments/',
  DeliveryItems: '/DeliveryItems/',
  DeliveryItemsIncrement: '/DeliveryItems/increment/',
  DeliveryItemsDecrement: '/DeliveryItems/decrement/',
  TemporaryModel: '/TemporaryModel/',
  DeliveryItemAddToStorage: '/DeliveryItems/addToStorage/',
} as const;

export const URLKEYS = {
  Manufacturers: 'Manufacturers',
  Models: 'Models',
  Bikes: 'Bikes',
  Bikes2: 'Bikes2',
  WheelSizes: 'WheelSizes',
  Colors: 'Colors',
  Categories: 'Categories',
  Statuses: 'Statuses',
  PlacesNotStorage: 'PlacesNotStorage',
  Places: 'Places',
  Employees: 'Employees',
  Users: 'Users',
  Repairs: 'Repairs',
  Services: 'Services',
  Units: 'Units',
  Parts: 'Parts',
  PartCategories: 'PartCategories',
  PartTypes: 'PartTypes',
  ServiceCategories: 'ServiceCategories',
  Favorites: 'Favorites',
  ExcludedStatuses: 'ExcludedStatuses',
  SoldBikes: 'SoldBikes',
  ServicesFromCategory: 'ServicesFromCategory',
  FilteredParts: 'FilteredParts',
  NotAssignedInvoice: 'NotAssignedInvoice',
  Invoice: 'Invoice',
  Invoices: 'Invoices',
  Deliveries: 'Deliveries',
  StartDelivery: 'StartDelivery',
  FinishDelivery: 'FinishDelivery',
  CancelDelivery: 'CancelDelivery',
  Delivery: 'Delivery',
  DeliveryDocuments: 'DeliveryDocuments',
  DeliveryItems: 'DeliveryItems',
  DeliveryItemsIncrement: 'DeliveryItemsIncrement',
  DeliveryItemsDecrement: 'DeliveryItemsDecrement',
  TemporaryModel: 'TemporaryModel',
  DeliveryItemAddToStorage: 'DeliveryItemAddToStorage',
} as const;
export default URLS;
