const URLS = {
  Manufacturers: "/Manufacturers/",
  Models: "/Models/",
  Bikes: "/Bikes/bikesByModelId/",
  Bikes2: "/Bikes/",
  WheelSizes: "/WheelSizes/",
  Colors: "/Colors/",
  Categories: "/Categories/",
  Statuses: "/Statuses/",
  PlacesNotStorage: "/Places/NotStorage/",
  Places: "/Places/",
  Employees: "/Employees/",
  Users: "/Users/",
  Repairs: "/Repairs/",
  Services: "/Services/",
  Units: "/Units/",
  Parts: "/Parts/",
  PartCategories: "/PartTypes/Categories/",
  PartTypes: "/PartTypes/",
  ServiceCategories: "/Services/Categories/",
  Favorites: "/Favorites/",
  ExcludedStatuses: "/Statuses/Excluded/",
  SoldBikes: "/SalesData/Sold/",
  ServicesFromCategory: "/Services/FromCategory/",
  FilteredParts: "/Parts/Filtered/"
};

export const URLKEYS = {
  Manufacturers: "Manufacturers",
  Models: "Models",
  Bikes: "Bikes",
  Bikes2: "Bikes2",
  WheelSizes: "WheelSizes",
  Colors: "Colors",
  Categories: "Categories",
  Statuses: "Statuses",
  PlacesNotStorage: "PlacesNotStorage",
  Places: "Places",
  Employees: "Employees",
  Users: "Users",
  Repairs: "Repairs",
  Services: "Services",
  Units: "Units",
  Parts: "Parts",
  PartCategories: "PartCategories",
  PartTypes: "PartTypes",
  ServiceCategories: "ServiceCategories",
  Favorites: "Favorites",
  ExcludedStatuses: "ExcludedStatuses",
  SoldBikes: "SoldBikes",
  ServicesFromCategory: "ServicesFromCategory",
  FilteredParts: "FilteredParts"

}
export default URLS;