'use client';
import DeliveryDisplay from '../../../components/delivery/DeliveryDisplay';
import { Delivery, DeliveryStatus } from '../../../types/deliveryTypes';

const DeliveryPage = ({ params }: { params: { id: string } }) => {
  const delivery: Delivery = {
    id: Number(params.id),
    plannedArrivalDate: new Date(),
    startDate: new Date(),
    finishDate: null,
    invoiceId: 1,
    placeId: 1,
    status: DeliveryStatus.InProgress,
    deliveryDocuments: [
      {
        id: 1,
        date: new Date(),
        name: 'Dokument Dostawy 1',
        items: [
          {
            id: 1,
            deliveryDocumentId: 1,
            modelId: 1,
            temporaryModelId: null,
            count: 5,
            storageCount: 5,
            deliveryModel: {
              id: 1,
              productCode: 'PRD-001',
              eanCode: '1234567890123',
              name: 'Rower Miejski',
              frameSize: 19,
              isWoman: false,
              wheelSizeId: 1,
              manufacturerId: 1,
              colorId: 1,
              categoryId: 1,
              primaryColor: '#000000',
              secondaryColor: '#C0C0C0',
              price: 1500,
              isElectric: false,
              link: '',
              insertionDate: new Date(),
              manufacturer: { id: 1, name: 'Producent A', order: 1 },
              color: { id: 1, name: 'Czarny', color: '#000000', order: 1 },
              category: { id: 1, name: 'Miejskie', order: 1 },
              wheelSize: { id: 1, name: '28', order: 1 },
            },
          },
          {
            id: 2,
            deliveryDocumentId: 1,
            modelId: 2,
            temporaryModelId: null,
            count: 3,
            storageCount: 7,
            deliveryModel: {
              id: 2,
              productCode: 'PRD-002',
              eanCode: '9876543210987',
              name: 'Rower Górski',
              frameSize: 17,
              isWoman: true,
              wheelSizeId: 2,
              manufacturerId: 2,
              colorId: 2,
              categoryId: 2,
              primaryColor: '#0000FF',
              secondaryColor: '#FFFFFF',
              price: 2000,
              isElectric: false,
              link: '',
              insertionDate: new Date(),
              manufacturer: { id: 2, name: 'Producent B', order: 2 },
              color: { id: 2, name: 'Niebieski', color: '#0000FF', order: 2 },
              category: { id: 2, name: 'Górskie', order: 2 },
              wheelSize: { id: 2, name: '26', order: 2 },
            },
          },
        ],
      },
      {
        id: 2,
        date: new Date(),
        name: 'Dokument Dostawy 2',
        items: [
          {
            id: 3,
            deliveryDocumentId: 2,
            modelId: 3,
            temporaryModelId: null,
            count: 2,
            storageCount: 1,
            deliveryModel: {
              id: 3,
              productCode: 'PRD-003',
              eanCode: '1112223334445',
              name: 'Rower Szosowy',
              frameSize: 18,
              isWoman: false,
              wheelSizeId: 3,
              manufacturerId: 3,
              colorId: 3,
              categoryId: 3,
              primaryColor: '#FF0000',
              secondaryColor: '#000000',
              price: 2500,
              isElectric: false,
              link: '',
              insertionDate: new Date(),
              manufacturer: { id: 3, name: 'Producent C', order: 3 },
              color: { id: 3, name: 'Czerwony', color: '#FF0000', order: 3 },
              category: { id: 3, name: 'Szosowe', order: 3 },
              wheelSize: { id: 3, name: '28', order: 3 },
            },
          },
          {
            id: 4,
            deliveryDocumentId: 2,
            modelId: 4,
            temporaryModelId: null,
            count: -1,
            storageCount: 0,
            deliveryModel: {
              id: 4,
              productCode: 'PRD-004',
              eanCode: '5556667778889',
              name: 'Rower Dziecięcy',
              frameSize: 12,
              isWoman: null,
              wheelSizeId: 4,
              manufacturerId: 4,
              colorId: 4,
              categoryId: 4,
              primaryColor: '#00FF00',
              secondaryColor: '#FFFF00',
              price: 800,
              isElectric: false,
              link: '',
              insertionDate: new Date(),
              manufacturer: { id: 4, name: 'Producent D', order: 4 },
              color: { id: 4, name: 'Zielony', color: '#00FF00', order: 4 },
              category: { id: 4, name: 'Dziecięce', order: 4 },
              wheelSize: { id: 4, name: '20', order: 4 },
            },
          },
        ],
      },
    ],
    invoice: {
      id: 1,
      invoiceNumber: 'FV/2024/01/001',
      issueDate: new Date(),
      paymentDate: new Date(),
      issuerName: 'Firma XYZ',
      issuerAddress: 'ul. Przykładowa 1, 00-000 Miasto',
      nettoAmount: 1000,
      bruttoAmount: 1230,
      deliveryId: 1,
    },
    place: {
      id: 1,
      name: 'Magazyn Główny',
      order: 1,
    },
  };

  return <DeliveryDisplay delivery={delivery} />;
};

export default DeliveryPage;
