
import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { MyQueryProvider } from "@/components/my_query_provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  const queryClient = new QueryClient();
  return (
    <MyQueryProvider>
      <html lang="en">
        <body className={inter.className + ' h-full overflow-auto'}>{children}</body>
      </html>
    </MyQueryProvider>
  );
}
